<?php

function members_menu(){
    $items['import/%/guidelines'] = array(
    'title' => 'Members Guidelines',
    'page callback' => 'node_page_view',
    'page arguments' => array(node_load(906)),
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
    'weight' => -13

    );

    $items['import/%/visitors_guidelines'] = array(
    'title' => 'Visitors Guidelines',
    'page callback' => 'node_page_view',
    'page arguments' => array(node_load(6009)),
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
    'weight' => -13

    );

return $items;
}


function members_form_members_node_form_alter(&$form, &$form_state, $form_id) {
// kpr($form);
    $form['field_tel_no_']['und'][0]['value']['#maxlength'] = '10';
    $form['field_tel_no_']['und'][1]['value']['#maxlength'] = '10';

  foreach($form['field_small_group']['und']['#options'] as &$option){
     $option = decode_entities($option);
  }

  unset($form['field_gender']['und']['#options']['_none']);
  drupal_set_title(t('Members'));

if(count($form['field_church_']['und']['#options']) > 1){
   $form['field_church_']['und']['#required'] = TRUE;
 }
else{
 unset($form['field_church_']);
 }

return $form;
}



function members_form_prospects_node_form_alter(&$form, &$form_state, $form_id) {
  foreach($form['field_small_group']['und']['#options'] as &$option){
     $option = decode_entities($option);
  }

unset($form['field_gender']['und']['#options']['_none']);
drupal_set_title(t('Prospects'));

if (count($form['field_church_']['und']['#options']) > 1){
   $form['field_church_']['und']['#required'] = TRUE;
 }
else{
   //$form['field_church_']['und']['#required'] = FALSE;
 unset($form['field_church_']);
 }

return $form;
}


function members_form_visitors_node_form_alter(&$form, &$form_state, $form_id) {
  foreach($form['field_small_group']['und']['#options'] as &$option){
     $option = decode_entities($option);
  }
  unset($form['field_gender']['und']['#options']['_none']);
  unset($form['field_visitor_decision']['und']['#options']['_none']);
drupal_set_title(t('Visitors'));

if (count($form['field_church_']['und']['#options']) > 1){
   $form['field_church_']['und']['#required'] = TRUE;
 }
else{
  // $form['field_church_']['und']['#required'] = FALSE;
   unset($form['field_church_']);
 }

return $form;
}

function members_form_report_node_form_alter(&$form, &$form_state, $form_id) {
drupal_set_title(t('Service Report'));
if (count($form['field_church_']['und']['#options']) > 1){
   $form['field_church_']['und']['#required'] = FALSE;
 }
else{
  // $form['field_church_']['und']['#required'] = FALSE;
   unset($form['field_church_']);
 }

return $form;
}


function members_form_family_members_node_form_alter(&$form, &$form_state, $form_id) {
drupal_set_title(t('Family'));

return $form;
}

function members_form_attendance_node_form_alter(&$form, &$form_state, $form_id) {
drupal_set_title(t('Attendance'));
$form['field_name_of_member']['und']['add_more']['#value'] = decode_entities('&#xf007;').' Add Members';
$form['field_attendance_']['und']['#options'][53] = 'Absent '. decode_entities('&#xf00d;');
$form['field_attendance_']['und']['#options'][52] = 'Present '. decode_entities('&#xf00c;');
return $form;
}


function members_form_visitors_attendance_node_form_alter(&$form, &$form_state, $form_id) {
drupal_set_title(t('Visitor Attendance'));
$form['field_visitor']['und']['add_more']['#value'] = decode_entities('&#xf007;').' Add Visitors';
$form['field_attendance_visitor']['und']['#options'][259] = 'Absent '. decode_entities('&#xf00d;');
$form['field_attendance_visitor']['und']['#options'][260] = 'Present '. decode_entities('&#xf00c;');
unset($form['field_attendance_visitor']['und']['#options']['_none']);
return $form;
}

// VBO label change
function members_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter') {
    if(isset($implementations['members'])){
      $group = $implementations['members'];
      unset($implementations['members']);
      $implementations['members'] = $group;
    }
  }
}


//Send mail for members page
  function members_form_views_form_members_page_alter(&$form, &$form_state, $form_id){

    $form['from']['views_send_from_name']['#default_value'] = '';
    $form['from']['views_send_from_mail']['#default_value'] = '';
    $form['to']['views_send_to_name']['#title'] = 'Select Name Option';
    $form['to']['views_send_to_mail']['#title'] = 'Select Email Option';

    $form['to']['views_send_to_name']['#options']['views_php_5_pos_5'] = 'Name';
    unset($form['to']['views_send_to_name']['#options']['node_title_pos_3']);
    unset($form['to']['views_send_to_name']['#options']['field_name_pos_5']);
    unset($form['to']['views_send_to_name']['#options']['counter_pos_2']);
    unset($form['to']['views_send_to_name']['#options']['field_tel_no__pos_7']);
    unset($form['to']['views_send_to_name']['#options']['nid_pos_13']);
    unset($form['to']['views_send_to_name']['#options']['nid_pos_14']);
    unset($form['to']['views_send_to_name']['#options']['nid_pos_4']);
    unset($form['to']['views_send_to_name']['#options']['path_pos_9']);
    unset($form['to']['views_send_to_name']['#options']['nid_pos_6']);
    unset($form['to']['views_send_to_name']['#options']['comments_link_pos_10']);
    unset($form['to']['views_send_to_name']['#options']['field_memail_pos_8']);
    unset($form['to']['views_send_to_name']['#options']['node_comment_statistics_comment_count_pos_11']);
    unset($form['to']['views_send_to_name']['#options']['history_timestamp_pos_6']);
    unset($form['to']['views_send_to_name']['#options']['field_new_member_pos_15']);
    unset($form['to']['views_send_to_name']['#options']['node_new_comments_pos_12']);


    $form['to']['views_send_to_mail']['#options']['field_memail_pos_8'] = 'Email';
    unset($form['to']['views_send_to_mail']['#options']['views_php_5_pos_5']);
    unset($form['to']['views_send_to_mail']['#options']['counter_pos_2']);
    unset($form['to']['views_send_to_mail']['#options']['nid_pos_6']);
    unset($form['to']['views_send_to_mail']['#options']['nid_pos_4']);
    unset($form['to']['views_send_to_mail']['#options']['node_title_pos_3']);
    unset($form['to']['views_send_to_mail']['#options']['field_name_pos_5']);
    unset($form['to']['views_send_to_mail']['#options']['field_tel_no__pos_7']);
    unset($form['to']['views_send_to_mail']['#options']['nid_pos_8']);
    unset($form['to']['views_send_to_mail']['#options']['comments_link_pos_10']);
    unset($form['to']['views_send_to_mail']['#options']['path_pos_9']);
    unset($form['to']['views_send_to_mail']['#options']['node_comment_statistics_comment_count_pos_11']);
    unset($form['to']['views_send_to_mail']['#options']['history_timestamp_pos_6']);
    unset($form['to']['views_send_to_mail']['#options']['node_new_comments_pos_12']);
    unset($form['to']['views_send_to_mail']['#options']['nid_pos_13']);
    unset($form['to']['views_send_to_mail']['#options']['nid_pos_14']);
    unset($form['to']['views_send_to_mail']['#options']['field_email_pos_7']);
    unset($form['to']['views_send_to_mail']['#options']['field_new_member_pos_15']);

    if ($form_state['view']->name == 'members' && $form_id == 'views_exposed_form') {
    $form['#action'] = 'test/members';
   }

  }

// function members_form_views_form_group_chnage_page_alter(&$form, &$form_state, $form_id){
//     // Adjust VBO text labels and set button weightings
//   // Set button order with #weight
//   if (isset($form['select']) && $form['select']['#title'] == 'Operations') {
//     // Adjust text
//     $form['select']['#title'] = t('Choose An Action');
//   }
//   if (isset($form['select']['action::views_bulk_operations_delete_item'])) {
//       $form['select']['action::views_bulk_operations_delete_item']['#weight'] = 10;
//     }
//   $form['properties']['name']['#description'] = 'Enter new name';
//   }

function members_form_comment_node_visitors_form_alter(&$form, &$form_state, $form_id){
// unset($form['author']['_author']['#title']);
// unset($form['author']['_author']['#markup']);
$form['feedback']['#markup'] = '<div class="feeback"><ul><li>Reasons for absence from the service</li><li>Follow up activities and feddback</li><li>Prayer requests</li><li>Needs and challenges</li><li>Other comments that will aid the assimilation of this visitor(guest)</li></ul></div>';
$form['feedback']['#weight'] = '-3';
return $form;
}

function members_form_user_login_alter(&$form, &$form_state, $form_id){
drupal_set_title(t('Log into FlockState'));
$form['name']['#placeholder'] = decode_entities('&#xf007;');
$form['pass']['#placeholder'] = decode_entities('&#xf084;');
$form['reset']['#markup'] = '<p>Forgot your password? <a href="/user/password">Reset it</a></p>';
return $form;
}

function members_form_user_register_form_alter(&$form, &$form_state, $form_id) {
  dpm($form);

  $form['account']['read']['#markup'] = '<div class="reado"><p class="read">Enter details of Account Administrator in the form below</p></div>';
  $form['account']['read']['#weight'] = -12;
  $form['account']['notify']['#default_value'] = TRUE;
  $form['account']['field_full_name'] = $form['field_full_name'];
  $form['account']['field_full_name']['#weight'] = -15;
  unset($form['field_full_name']);

  if(user_is_anonymous()) {
    $form['account']['#title'] = "User Account";
      $form['field_phone_nos']['und'][0]['value']['#required'] = TRUE;
       $form['field_domain_ministry']['und'][0]['value']['#required'] = TRUE;
       $form['field_name_of_ministry']['und'][0]['value']['#required'] = TRUE;
       $form['field_address_of_minstry']['und'][0]['value']['#required'] = TRUE;
  }
$form['field_domain_ministry']['#prefix'] = '<div class="prefix"><div class="oop">http://</div>';
$form['field_domain_ministry']['#suffix'] = '<div class="ooo">.flockstate.com</div></div>';

  return $form;


}

function members_form_profile2_edit_ministry_account_form_alter(&$form, &$form_state){

if(user_is_anonymous()) {
      $form['profile_ministry_account']['field_phone']['und'][0]['value']['#required'] = TRUE;


  }

  return $form;
}

function members_date_popup_process_alter(&$element, &$form_state, $context) {

  unset($element['date']['#description']);
  unset($element['date']['#title']);

}

function members_field_formatter_info() {
  return array(
    'taxonomy_term_reference_link_with_class' => array(
      'label' => t('Link with class'),
      'field types' => array('taxonomy_term_reference'),
    ),
    'taxonomy_term_reference_plain_with_class' => array(
      'label' => t('Plain text with class'),
      'field types' => array('taxonomy_term_reference'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function members_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  // Terms whose tid is 'autocreate' do not exist
  // yet and $item['taxonomy_term'] is not set. Theme such terms as
  // just their name.

  switch ($display['type']) {
    case 'taxonomy_term_reference_link_with_class':
      foreach ($items as $delta => $item) {
        if ($item['tid'] == 'autocreate') {
          $element[$delta] = array(
            '#value' => check_plain($item['name']),
            '#theme' => 'html_tag',
            '#tag' => 'span',
            '#attributes' => array(
              'class' => array('term-tid-new'),
            ),
          );
        }
        else {
          $term = $item['taxonomy_term'];
          $uri = entity_uri('taxonomy_term', $term);
          $uri['options']['attributes']['class'][] = 'term-tid-' . $term->tid;
          $element[$delta] = array(
            '#type' => 'link',
            '#title' => $term->name,
            '#href' => $uri['path'],
            '#options' => $uri['options'],
          );
        }
      }

      break;

    case 'taxonomy_term_reference_plain_with_class':
      foreach ($items as $delta => $item) {
        $name = ($item['tid'] != 'autocreate' ? $item['taxonomy_term']->name : $item['name']);
        $tid = ($item['tid'] != 'autocreate' ? $item['taxonomy_term']->tid : 'new');
        $element[$delta] = array(
          '#value' => check_plain($name),
          '#theme' => 'html_tag',
          '#tag' => 'span',
          '#attributes' => array(
            'class' => array('term-tid-' . $tid),
          ),
        );
      }
      break;
  }

  return $element;
}

/**
 * Implements hook_field_formatter_prepare_view().
 *
 * This preloads all taxonomy terms for multiple loaded objects at once and
 * unsets values for invalid terms that do not exist.
 */
function members_field_formatter_prepare_view($entity_type, $entities, $field, $instances, $langcode, &$items, $displays) {
  // Call prepare view formatter for a taxonomy term
  taxonomy_field_formatter_prepare_view($entity_type, $entities, $field, $instances, $langcode, $items, $displays);
}

//Contact form alter
function members_form_contact_site_form_alter(&$form, &$form_state, $form_id) {
$form['name']['#title'] = 'Name';
$form['mail']['#title'] = 'Email';

return $form;
}

//feeds import alter
function members_feeds_presave(FeedsSource $source, $entity, $item) {
  if (($entity->type == 'visitors') || ($entity->type == 'prospects') || ($entity->type == 'members')) {
    global $user;
    $entity->uid = $user->uid;
  }
}

// Visitors Attendance form alter
function members_form_alter(&$form, &$form_state, $form_id) {

    if($form_id == 'members_node_form'){
        $form['#validate'][] = 'members_form_validate';
    }
    // dpm($form_state);
// if($form_id == 'visitors_attendance_node_form'){
//   $form['field_visitor'][LANGUAGE_NONE]['add_more']['#value'] = 'Add Visitors';
// }

if(($form_id == 'views_form_members_church') || ($form_id == 'views_form_members_ministry') || ($form_id == 'views_form_members_groups') || ($form_id == 'views_form_new_members_church') || ($form_id == 'views_form_new_members_all_guests') || ($form_id == 'views_form_members_group') || ($form_id == 'views_form_prospects_ministry') || ($form_id == 'views_form_prospects_church') || ($form_id == 'views_form_prospects_group')) {

    // Adjust VBO text labels and set button weightings
  // Set button order with #weight
  if (isset($form['select']) && $form['select']['#title'] == 'Operations') {
    // Adjust text
    $form['select']['#title'] = t('Choose Action');
  }
}

  if(($form_id == 'views_form_members_church') || ($form_id == 'views_form_members_ministry') || ($form_id == 'views_form_members_groups')){

  //Alter Views Mail Form
  //Send to name
  unset($form['to']['views_send_to_name']['#options']['counter_pos_2']);
  unset($form['to']['views_send_to_name']['#options']['path_pos_10']);
  unset($form['to']['views_send_to_name']['#options']['nid_pos_11']);
  unset($form['to']['views_send_to_name']['#options']['nid_pos_12']);
  unset($form['to']['views_send_to_name']['#options']['nid_pos_4']);
  unset($form['to']['views_send_to_name']['#options']['field_name_pos_5']);
  unset($form['to']['views_send_to_name']['#options']['field_surname_pos_6']);
  unset($form['to']['views_send_to_name']['#options']['history_timestamp_pos_7']);
  unset($form['to']['views_send_to_name']['#options']['field_memail_pos_9']);
  unset($form['to']['views_send_to_name']['#options']['field_tel_no__pos_8']);
  unset($form['to']['views_send_to_name']['#options']['path_pos_10']);
  unset($form['to']['views_send_to_name']['#options']['comments_link_pos_11']);
  unset($form['to']['views_send_to_name']['#options']['node_comment_statistics_comment_count_pos_12']);
  unset($form['to']['views_send_to_name']['#options']['node_new_comments_pos_13']);
  unset($form['to']['views_send_to_name']['#options']['nid_pos_14']);
  unset($form['to']['views_send_to_name']['#options']['nid_pos_15']);
   $form['to']['views_send_to_name']['#options']['node_title_pos_3'] = 'Name';

  unset($form['to']['views_send_to_mail']['#options']['counter_pos_2']);
  unset($form['to']['views_send_to_mail']['#options']['path_pos_10']);
  unset($form['to']['views_send_to_mail']['#options']['nid_pos_11']);
  unset($form['to']['views_send_to_mail']['#options']['nid_pos_12']);
  unset($form['to']['views_send_to_mail']['#options']['nid_pos_4']);
  unset($form['to']['views_send_to_mail']['#options']['field_name_pos_5']);
  unset($form['to']['views_send_to_mail']['#options']['field_surname_pos_6']);
  unset($form['to']['views_send_to_mail']['#options']['history_timestamp_pos_7']);
  $form['to']['views_send_to_mail']['#options']['field_memail_pos_9'] = 'Email';
  unset($form['to']['views_send_to_mail']['#options']['node_title_pos_3']);
  unset($form['to']['views_send_to_mail']['#options']['field_tel_no__pos_8']);
  unset($form['to']['views_send_to_mail']['#options']['path_pos_10']);
  unset($form['to']['views_send_to_mail']['#options']['comments_link_pos_11']);
  unset($form['to']['views_send_to_mail']['#options']['node_comment_statistics_comment_count_pos_12']);
  unset($form['to']['views_send_to_mail']['#options']['node_new_comments_pos_13']);
  unset($form['to']['views_send_to_mail']['#options']['nid_pos_14']);
   }

if(($form_id == 'views_form_new_members_church') || ($form_id == 'views_form_new_members_all_guests') || ($form_id == 'views_form_new_members_group')){
  //Alter Views Mail Form
  //Send to name
  unset($form['to']['views_send_to_mail']['#options']['counter_pos_2']);
  unset($form['to']['views_send_to_name']['#options']['counter_pos_2']);
  $form['to']['views_send_to_name']['#options']['node_title_pos_3'] = 'Name';
  unset($form['to']['views_send_to_name']['#options']['history_timestamp_pos_4']);
  unset($form['to']['views_send_to_name']['#options']['field_tel_no__pos_5']);
  unset($form['to']['views_send_to_name']['#options']['field_memail_pos_6']);
  unset($form['to']['views_send_to_name']['#options']['nid_pos_7']);
  unset($form['to']['views_send_to_name']['#options']['path_pos_8']);
  unset($form['to']['views_send_to_name']['#options']['comments_link_pos_9']);
  unset($form['to']['views_send_to_name']['#options']['node_comment_statistics_comment_count_pos_10']);
  unset($form['to']['views_send_to_name']['#options']['nid_pos_11']);
  unset($form['to']['views_send_to_name']['#options']['nid_pos_12']);
  unset($form['to']['views_send_to_name']['#options']['node_new_comments_pos_13']);
  unset($form['to']['views_send_to_name']['#options']['field_address_pos_14']);

  unset($form['to']['views_send_to_mail']['#options']['node_title_pos_3']);
  unset($form['to']['views_send_to_mail']['#options']['history_timestamp_pos_4']);
  unset($form['to']['views_send_to_mail']['#options']['field_tel_no__pos_5']);
  $form['to']['views_send_to_mail']['#options']['field_memail_pos_6'] = 'Email';
  unset($form['to']['views_send_to_mail']['#options']['nid_pos_7']);
  unset($form['to']['views_send_to_mail']['#options']['path_pos_8']);
  unset($form['to']['views_send_to_mail']['#options']['comments_link_pos_9']);
  unset($form['to']['views_send_to_mail']['#options']['node_comment_statistics_comment_count_pos_10']);
  unset($form['to']['views_send_to_mail']['#options']['nid_pos_11']);
  unset($form['to']['views_send_to_mail']['#options']['nid_pos_12']);
  unset($form['to']['views_send_to_mail']['#options']['node_new_comments_pos_13']);
  unset($form['to']['views_send_to_mail']['#options']['field_address_pos_14']);
   }

if(($form_id == 'views_form_new_members_all_guests') || ($form_id == 'views_form_members_group') || ($form_id == 'views_form_prospects_ministry') || ($form_id == 'views_form_prospects_church') || ($form_id == 'views_form_prospects_group')){

  //Alter Views Mail Form
  //Send to name


  unset($form['to']['views_send_to_name']['#options']['counter_pos_2']);
  unset($form['to']['views_send_to_name']['#options']['nid_pos_7']);
  unset($form['to']['views_send_to_name']['#options']['nid_pos_8']);
  unset($form['to']['views_send_to_name']['#options']['field_memail_pos_6']);
  unset($form['to']['views_send_to_name']['#options']['field_tel_no__pos_5']);
   unset($form['to']['views_send_to_name']['#options']['field_address_pos_4']);
   $form['to']['views_send_to_name']['#options']['node_title_pos_3'] = 'Name';

  unset($form['to']['views_send_to_mail']['#options']['counter_pos_2']);
  unset($form['to']['views_send_to_mail']['#options']['nid_pos_7']);
  unset($form['to']['views_send_to_mail']['#options']['nid_pos_8']);
  $form['to']['views_send_to_mail']['#options']['field_memail_pos_6'] = 'Email';
  unset($form['to']['views_send_to_mail']['#options']['field_tel_no__pos_5']);
   unset($form['to']['views_send_to_mail']['#options']['field_address_pos_4']);
  unset($form['to']['views_send_to_mail']['#options']['node_title_pos_3']);

   }


return $form;
}

function members_form_validate($node, $form, &$form_state){
   dpm($form_state);

}

 function members_form_views_exposed_form_alter(&$form, $form_state) {
  $form['date_filter_1']['value']['#date_format'] = 'm/d/Y';
  $form['date_filter']['value']['#date_format'] = 'm/d/Y';
  $form['date_filter']['min']['#date_format'] = 'm/d/Y';
  $form['date_filter']['max']['#date_format'] = 'm/d/Y';
  $form['date_filter_1']['min']['#date_format'] = 'm/d/Y';
  $form['date_filter_1']['max']['#date_format'] = 'm/d/Y';
  $form['date_filter_2']['value']['#date_format'] = 'm/d/Y';
  $form['tid']['#options'][53] = 'Absent '. decode_entities('&#xf00d;');
  $form['tid']['#options'][52] = 'Present '. decode_entities('&#xf00c;');
     $form['tid']['#options'][259] = 'Absent '. decode_entities('&#xf00d;');
  $form['tid']['#options'][260] = 'Present '. decode_entities('&#xf00c;');
     if(count($form['field_church__tid']['#options']) < 2){
    unset($form['field_church__tid']);
    unset($form['#info']['filter-field_church__tid']['label']);
  }

}

function members_form_user_profile_form_alter(&$form, &$form_state, $form_id){


if(count($form['field_church_']['und']['#options']) > 2) {
  unset($form['field_church_']);
  // unset($form['account']['roles']['#options'][4]);

}
// if(!isset($form['field_church_'])){
//    // unset($form['account']['roles_change']['#options'][4]);
// }
if(($form['account']['roles']['#default_value'][0] == 2) && ($form['account']['roles']['#default_value'][1] == 10)){
   unset($form['field_church_']);
}

return $form;
}

// Rules queue mail
/**
* Implements hook_cron_queue_info().
*/
// function members_cron_queue_info() {
// $queues = array();
// $queues['members_queue_notify'] = array(
// 'worker callback' => 'members_queue_notify_worker',
// 'time' => 90,
// );
// return $queues;
// }

// /**
// * Queue worker for sending notification mails.
// */
// function members_queue_notify_worker($params) {
// drupal_mail('members', 'notify', $params['to'], language_default(), $params, $params['from']);
// }

// /**
// * Implements hook_mail().
// */
// function members_mail($key, &$message, $params) {
// $language = $message['language'];
// $message['subject'] = $params['subject'];
// $message['body'][] = $params['message'];
// }

// /**
// * Implements hook_rules_action_info().
// */
// function members_rules_action_info() {
// return array(
// 'members_rules_action_mail' => array(
// 'label' => t('Send mail'),
// 'group' => 'members',
// 'parameter' => array(
// 'to' => array(
// 'type' => 'text',
// 'label' => t('To'),
// 'description' => t('The e-mail address or addresses where the message will be sent to. The formatting of this string must comply with RFC 2822.'),
// ),
// 'subject' => array(
// 'type' => 'text',
// 'label' => t('Subject'),
// 'description' => t("The mail's subject."),
// ),
// 'message' => array(
// 'type' => 'text',
// 'label' => t('Message'),
// 'description' => t("The mail's message body."),
// ),
// 'from' => array(
// 'type' => 'text',
// 'label' => t('From'),
// 'description' => t("The mail's from address. Leave it empty to use the site-wide configured address."),
// 'optional' => TRUE,
// ),
// ),
// ),
// );
// }

// /**
// * Action: Add notification mails to the queue.
// */
// function members_rules_action_mail($to, $subject, $message, $from = NULL, $settings, RulesState $state, RulesPlugin $element) {
// // Gather params.
// $params = array(
// 'to' => str_replace(array("\r", "\n"), '', $to),
// 'from' => !empty($from) ? str_replace(array("\r", "\n"), '', $from) : NULL,
// 'subject' => $subject,
// 'message' => $message,
// );
// // Add to the queue.
// $queue = DrupalQueue::get('members_queue_notify');
// $queue->createItem($params);
// }

function members_form_comment_node_members_form_alter(&$form, &$form_state, $form_id){
$form['feedback']['#markup'] = '<div class="feeback"><ul><li>Reasons for absence from the service</li><li>Follow up activities and feddback</li><li>Prayer requests</li><li>Needs and challenges</li><li>Other comments that will aid the welfare and care of this member</li></ul></div>';
$form['feedback']['#weight'] = '-3';
  return $form;
}


function members_views_plugins_alter(&$plugins) {
  $plugins['style']['views_data_export_xls']['export feed icon'] = 'sites/default/files/xlsx.png';
   $plugins['style']['views_data_export_txt']['export feed icon'] = 'sites/default/files/txts.png';
}

// function members_views_query_alter(&$view, &$query){
//   if($view->name == 'members'){
//     $query->where[0]['type'] = 'OR';
//   }
// }

// function members_views_api(){
//   return array(
//     'api' => 3,
// );
// }


//Cloning Rules
function members_rules_action_info() {
  $defaults = array(
    'parameter' => array(
       'source_node' => array(
         'type' => 'node',
         'label' => t('Source Node'),
       ),
    ),
    'provides' => array(
       'type' => 'node',
       'label' => t("Cloned Node's Original node"),
    ),
    'group' => t('Node'),
  );

  $actions['clone_orig_node'] = $defaults + array(
    'label' => t('Get original node'),
    'base' => 'members_action_get_orig_node',
  );

  return $actions;
}

/**
 * Implements hook_rules_condition_info
 */
function members_rules_condition_info() {
  $defaults = array(
    'parameter' => array(
      'cloned_node' => array(
        'type' => 'node',
        'label' => t('Node to check'),
      ),
    ),
    'group' => t('Node'),
  );

  $conditions['user_block'] = $defaults + array(
    'label' => t('Node is cloned'),
    'base' => 'members_condition_node_is_cloned',
  );

  return $conditions;
}

/**
 * Rules condition to determine whether node is cloned or not.
 *
 * @param Node $node
 * Node to check.
 * @return boolean
 * True if node is cloned, false otherwise.
 */
function members_condition_node_is_cloned($node) {
  return isset($node->clone_from_original_nid) ? TRUE : FALSE;
}

/**
 * Rules action to load original node by which $node is cloned.
 *
 * @param node $node
 * The cloned node.
 * @return Node
 * The original node by which $node is cloned.
 */
function members_action_get_orig_node($node) {
  if(members_condition_node_is_cloned($node)) {
    return node_load($node->clone_from_original_nid);
  }
  return FALSE;
}


/**
 * Implements hook_menu().
 *
 * This module allows to create a menu item that links to a file that is in the downloads folder
 */

function members_user_login(&$edit, $account){
  drupal_set_message(t('Hello @user'));
}

function members_views_data_alter(&$data) {

  $data['users']['username'] = array(
    'title' => t('Username'),
    'help' => t("The user or author username."),
    'real field' => 'name',
    'field' => array(
      'handler' => 'views_handler_field_user',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
      'title' => t('Name'),
      'help' => t("The user's actual, raw, username.")
    ),
  );
}
//
//function members_user_insert(&$edit, $account, $category){
//    $domain = domain_get_domain();
//
//    $query = db_insert('domain_editor')
//        ->fields(array('uid', 'domain_id'))
//        ->values(array('uid' => $account->uid, 'domain_id' => $domain['domain_id']));
//
//    $query->execute();
//
//}



